# PORGRAM INI DI TUJUKAN UNTUK MEMBANDINGKAN UMUR
#DARI USIA YANG DI ANJURKAN UNTUK MEROKOK

print("\t          (*====PROGRAM INI DI TUJUKAN UNTUK MEMBANDINGKAN DAN MENENTUKAN APAKAH USIA USER SUDAH MENCUKUPI UNTUK MENGONSUMSI ROKOK====*)")
print("")
print("PERINGATAN MEROKOK AKAN MEMBUNUMU SECARA PERLAHAN!!!")
print("")
print("WARNING!!!, CIGARETTE WILL KILL YOU SLOWLY!!!!")

user = int(input("MASUKKAN USIA ANDA (hanya dalam bentuk angka)!! : "))
usia = 18
print("")
print("")
print("JIKA PROSES MENGAHASILKAN ==FALSE== MAKA ANDA DALAM USIA DI BAWAH DINI UNTUK MEROKOK")
print("DAN JIKA ANDA HASILNYA ==TRUE== MAKA ANDA SUDAH MASUK KATEGORI CUKUP DEWASA UNTUK MEROKOK")
print("")
print("")
PAUSE = input("TEKAN enter UNTUK MELANJUTKAN")
print("")
print("")
# MASUK KEPADA VARIABEL OPERASI DAN OUTPUT
print("")
print("")
hasil = user >= usia

if(usia > user):
    print("USIA USER YANG ({}) DAN USIA YANG DI TETAPKAN ({}) MEMILIKI HASIL ({}) YANG ARTINYA ANDA BELUM CUKUP DEWASA UNTUK MEROKOK".format(user, usia, hasil))
if(usia <= user):
    print("USIA USER YANG ({}) DAN USIA YANG DI TETAPKAN ({}) MEMILIKI HASIL ({}) YANG HASILNYA ANDA SUDAH CUKUP DEWASA UNTUK UNTUK MEROKOK".format(user, usia, hasil))

